### ISSUE TITLE
Release Date ?

### ISSUE THREAD

**Issue by FuxonPlayz** [Survingo/LuckyBlockWars#3]
When the plugin released ?

**Comment by Survingo** [comment]
You'll know it when it's visible in the PocketMine plugins library

**Comment by FuxonPlayz** [comment]
@Survingo lol u don't know ? Not Everyone Can Upload or Update Plugins on PocketMine Just Upload it on ImagicalMine Plugins Fourms

**Comment by Survingo** [comment]
I don't like copies of PocketMine, even if ImagicalMine is dead and their forums are just for plugins. Maybe I code that the plugin will disable if soneone doesn't uses PM-MP

**Comment by FuxonPlayz** [comment]
Will the most of people doesn't use official PocketMine anymore cause he's
dead and doesn't get updates

**Comment by Survingo** [comment]
What are you talking about? PocketMine-MP is up-to-date after one day of an update of MCPE

**Comment by FuxonPlayz** [comment]
Really ? OK go and see the latest commit on Github 😂

**Comment by FuxonPlayz** [comment]
Is this plugin usable ? Or still not implemented all the features ?

**Comment by Survingo** [comment]
PocketMine updated 1 month ago because it doesn't needs an update.
It's working for 0.14.99.0-0.15.3.2...

And this plugin is not usable yet I think

**Comment by FuxonPlayz** [comment]
Whatever are u going to finish the plugin soon ?

**Comment by Survingo** [comment]
Yep

**Comment by FuxonPlayz** [comment]
OK thx
