### ISSUE TITLE
Crash on startup

### ISSUE THREAD

**Issue by erkam2002** [Survingo/LuckyBlockWars#4]
Loading source plugin LuckyBlockWars vAlpha

Warning: Uncaught ClassNotFoundException: Class Survingo\LuckyBlockWars\CommandSender not found in phar://C:/Users/Kahriman/Desktop/Genisys/PocketMine-MP.phar/src/spl/BaseClassLoader.php:144
Stack trace:
#0 [internal function]: BaseClassLoader->loadClass('Survingo\\LuckyB...')
#1 C:\Users\Kahriman\Desktop\Genisys\plugins\LuckyBlockWars-master\src\Survingo\LuckyBlockWars\LuckyBlockWars.php(31): spl_autoload_call('Survingo\\LuckyB...')
#2 phar://C:/Users/Kahriman/Desktop/Genisys/PocketMine-MP.phar/src/spl/BaseClassLoader.php(128): include('C:\\Users\\Kahrim...')
#3 [internal function]: BaseClassLoader->loadClass('Survingo\\LuckyB...')
#4 [internal function]: spl_autoload_call('Survingo\\LuckyB...')
#5 phar://C:/Users/Kahriman/Desktop/Genisys/PocketMine-MP.phar/src/pocketmine/plugin/FolderPluginLoader.php(48): class_exists('Survingo\\LuckyB...', true)
#6 phar://C:/Users/Kahriman/Desktop/Genisys/PocketMine-MP.phar/src/pocketmine/plugin/PluginManager.php(155): pocketmine\plugin\FolderPluginLoader->loadPlugin('C:\\Users\\Ka in phar://C:/Users/Kahriman/Desktop/Genisys/PocketMine-MP.phar/src/spl/BaseClassLoader.php on line 144

Fatal error: Declaration of Survingo\LuckyBlockWars\LuckyBlockWars::onCommand(Survingo\LuckyBlockWars\CommandSender $sender, Survingo\LuckyBlockWars\Command $command, $label, array $args) must be compatible with pocketmine\command\CommandExecutor::onCommand(pocketmine\command\CommandSender $sender, pocketmine\command\Command $command, $label, array $args) in C:\Users\Kahriman\Desktop\Genisys\plugins\LuckyBlockWars-master\src\Survingo\LuckyBlockWars\LuckyBlockWars.php on line 31
[12:29:41] [Server thread/EMERGENCY]: An unrecoverable error has occurred and the server has crashed. Creating a crash dump
[12:29:41] [Server thread/EMERGENCY]: Please upload the "C:\Users\Kahriman\Desktop\Genisys\crashdumps/CrashDump_Mon_Aug_22-12.29.41-BST_2016.log" file to the Crash Archive and submit the link to the Bug Reporting page. Give as much info as you can.
****

**Comment by Survingo** [comment]
My plugins don't support forks of PockeMine.
Try PockeMine-MP 1.6dev

**Comment by erkam2002** [comment]
Oh pls implement Genisys
